### ISSUE TITLE
Drag and sort

### ISSUE THREAD

**Issue by rain20240327** [RavenHogWarts/obsidian-custom-icons#16]
yo, bro, I want to make a wish for a feature: Drag and sort
In this way, I can more easily see the icon effect between folders and folders.

**Comment by RavenHogWarts** [comment]
you mean like the "templater" plugin that moves up and down?
![image](https://github.com/RavenHogWarts/obsidian-custom-icons/assets/58649975/5a669ba6-aacd-4f2b-928d-af1718843fd1)

**Comment by rain20240327** [comment]
Yes, or like the way of rearranging in obsidian→Appearance→Ribbon menu, that would also work.
![截图_2024-05-22_23-27-05](https://github.com/RavenHogWarts/obsidian-custom-icons/assets/165189881/3c8a3646-85c4-4a60-a0ab-48c2310088b4)

**Comment by RavenHogWarts** [comment]
> Yes, or like the way of rearranging in obsidian→Appearance→Ribbon menu, that would also work. ![截图_2024-05-22_23-27-05](https://private-user-images.githubusercontent.com/165189881/332860383-3c8a3646-85c4-4a60-a0ab-48c2310088b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTM1MzksIm5iZiI6MTcxNjM5MzIzOSwicGF0aCI6Ii8xNjUxODk4ODEvMzMyODYwMzgzLTNjOGEzNjQ2LTg1YzQtNGE2MC1hMGFiLTQ4YzIzMTAwODhiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNTUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjc5MzM4MDlhZTA4YjQxOGE5NzMzMjhmYTRjYTc0YWI1NTBmMDcyNDZkNTFkYWM3M2RlYzc5MjgwZTJmYTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TXOrTNyLgcmvLYajgJP_pDk1GWO5TqsQp44KY9QbcZg)

Oh, thank you, my friend. I'll take your suggestion under advisement.

**Comment by rain20240327** [comment]
you are welcome
